find_path(LIBINIPARSER_INCLUDE_DIR ui.h "${LIBINIPARSER_DIR}/include")
find_library(LIBINIPARSER iniparser "${LIBINIPARSER_DIR}/lib")
set(LIBINIPARSER_LIBRARIES  ${LIBINIPARSER})
set(LIBINIPARSER_INCLUDE_DIRS ${LIBINIPARSER_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBINIPARSER DEFAULT_MSG LIBINIPARSER_LIBRARIES LIBINIPARSER_INCLUDE_DIR)

mark_as_advanced(LIBINIPARSER_INCLUDE_DIR LIBINIPARSER)
